// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Colors() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t:root {\n\t\t\t--bg-primary: #1a1a1a;\n\t\t\t--bg-secondary: #2d2d2d;\n\t\t\t--bg-tertiary: #3d3d3d;\n\t\t\t--text-primary: #e0e0e0;\n\t\t\t--text-secondary: #b0b0b0;\n\t\t\t--border-color: #404040;\n\t\t\t--shadow: rgba(0, 0, 0, 0.3);\n\t\t\t--hover-bg: #3d3d3d;\n\t\t\t--selected-bg: #2a4a6a;\n\t\t\t--changed-bg:rgba(96, 42, 115, 0.47);\n\t\t\t--primary-blue: #007bff;\n\t\t\t--primary-blue-hover: #0056b3;\n\t\t\t--success-green: #28a745;\n\t\t\t--warning-orange: #ff9800;\n\t\t\t--warning-orange-hover: #f57c00;\n\t\t\t--secondary-gray: #6c757d;\n\t\t\t--secondary-gray-hover: #5a6268;\n\t\t\t--disabled-gray: #ccc;\n\t\t\t--white: #ffffff;\n\t\t\t--modal-overlay: rgba(0, 0, 0, 0.5);\n\t\t\t--focus-blue: #007bff;\n\t\t\t--btn-text-active: #ffffff;\n\t\t\t--btn-text-inactive: rgba(255, 255, 255, 0.5);\n\t\t}\n\n\t\t[data-theme=\"light\"] {\n\t\t\t--bg-primary: #f5f5f5;\n\t\t\t--bg-secondary: #ffffff;\n\t\t\t--bg-tertiary: #f8f9fa;\n\t\t\t--text-primary: #333333;\n\t\t\t--text-secondary: #666666;\n\t\t\t--border-color: #dddddd;\n\t\t\t--shadow: rgba(0, 0, 0, 0.1);\n\t\t\t--hover-bg: #f8f9fa;\n\t\t\t--selected-bg: #e7f3ff;\n\t\t\t--changed-bg:rgba(199, 163, 243, 0.52);\n\t\t\t--primary-blue: #007bff;\n\t\t\t--primary-blue-hover: #0056b3;\n\t\t\t--success-green: #28a745;\n\t\t\t--warning-orange: #ff9800;\n\t\t\t--warning-orange-hover: #f57c00;\n\t\t\t--secondary-gray: #6c757d;\n\t\t\t--secondary-gray-hover: #5a6268;\n\t\t\t--disabled-gray: #ccc;\n\t\t\t--white: #ffffff;\n\t\t\t--modal-overlay: rgba(0, 0, 0, 0.5);\n\t\t\t--focus-blue: #007bff;\n\t\t\t--btn-text-active: #6c757d;\n\t\t\t--btn-text-inactive: rgba(108, 117, 125, 0.5);\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
