// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EditModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modal-overlay\" id=\"modalOverlay\" onclick=\"closeModalOnOverlay(event)\"><div class=\"modal-content\" onclick=\"event.stopPropagation()\"><div class=\"modal-header\"><h3>Edit Tags</h3></div><div class=\"modal-body\"><div class=\"form-group\"><label for=\"editTitle\">Title:</label> <input type=\"text\" id=\"editTitle\" placeholder=\"Enter track title\"></div><div class=\"form-group\"><label for=\"editArtist\">Artist:</label> <input type=\"text\" id=\"editArtist\" placeholder=\"Enter artist name\"></div><div class=\"form-group\"><label for=\"editAlbum\">Album:</label> <input type=\"text\" id=\"editAlbum\" placeholder=\"Enter album name\"></div><div class=\"form-group\"><label for=\"editYear\">Year:</label> <input type=\"number\" id=\"editYear\" placeholder=\"Enter year\" min=\"1900\" max=\"2100\"></div><div class=\"form-group\"><label for=\"editTrack\">Track:</label> <input type=\"number\" id=\"editTrack\" placeholder=\"Enter track number\" min=\"1\"></div><div class=\"form-group\"><label for=\"editGenre\">Genre:</label> <input type=\"text\" id=\"editGenre\" placeholder=\"Enter genre\"></div><div class=\"form-group\"><label for=\"editCoverArt\">Cover Art:</label> <input type=\"file\" id=\"editCoverArt\" accept=\"image/*\"><div id=\"coverPreview\" style=\"margin-top: 0.5rem;\"></div></div></div><div class=\"modal-footer\"><button class=\"btn-primary\" tabindex=\"0\" onclick=\"saveTags()\">Save</button> <button class=\"btn-secondary\" tabindex=\"0\" onclick=\"cancelEdit()\">Cancel</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
